### GET todos - v1
GET {{API_URL}}/v1/todos/
Authorization: Bearer {{auth_token}}
Accept: application/json

###

### GET user - v1
GET {{API_URL}}/v1/todos/fe78e132-0091-4343-860f-8acfead8371d
Accept: application/json
Authorization: Bearer {{auth_token}}

###

### POST user
POST {{API_URL}}/v1/todos

Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "data": {
        "type": "todos",
        "attributes": {
            "description": "Go Sailing",
            "userId": "88286ffd-509f-489c-b288-c8bcf411fad6",
        }
    }
}

###

### PUT user
PUT {{API_URL}}/v1/todos/fe78e132-0091-4343-860f-8acfead8371d
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "data": {
        "type": "todos",
        "attributes": {
            "description": "Go Sailing",
            "userId": "88286ffd-509f-489c-b288-c8bcf411fad6",
        }
    }
}

###

### PATCH user
PATCH {{API_URL}}/v1/todos/88286ffd-509f-489c-b288-c8bcf411fad6
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "data": {
        "type": "todos",
        "attributes": {
            "email": "popeye.the.sailor@example.com",
        }
    }
}

###

### DELETE user - v1
DELETE {{API_URL}}/v1/todos/818589e7-8fe7-4d2b-8cdb-e00a0dd49130
Accept: application/json
Authorization: Bearer {{auth_token}}

###
